version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - ./buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    ports:
      - "8111:8111"
    networks:
      - web
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    mem_limit: 2g
    depends_on:
      - db

  agent:
    container_name: agent
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}
    networks:
      - web
    volumes: 
    - ./agents/default-agent/conf:/data/teamcity_agent/conf
    environment:
    - SERVER_URL=http://192.168.0.17:8111
  
networks:
  web:
    external: true